name: Build Zip

on:
  push:
    branches:
      - '**'
    paths:
      - 'calibre-plugin/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'calibre-plugin/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: overdrive-libby-plugin-${{ github.sha }}
          path: |
            calibre-plugin/
            !calibre-plugin/translations/*.po
