name: Build Zip

on:
  push:
    branches:
      - '**'
    paths:
      - 'calibre-plugin/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'calibre-plugin/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1
      - name: Install gtext
        run: sudo apt-get -y install gettext
      - name: Build .mo files
        run: |
          cd .github/workflows
          sh build_translations.sh
      - name: Shorten GITHUB_SHA
        run: echo "github_short_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Upload plugin
        uses: actions/upload-artifact@v3
        with:
          name: overdrive-libby-plugin-${{ env.github_short_sha }}
          path: |
            calibre-plugin/
